import 'dart:io';

import 'package:flutter/material.dart';
import 'package:singbox_tunnel/singbox_tunnel.dart';

import 'config/config.dart';
import 'package:provider/provider.dart';

import 'transport/dartssh2_transport.dart';
import 'tunnel/unimplemented_tunnel.dart';
import 'ui/app.dart';
import 'ui/missing_backend.dart';
import 'ui/models.dart';
import 'ui/ports.dart';
import 'ui/server_store.dart';

/// The composition root, and the only file that names an implementation.
///
/// Every screen below here depends on the interfaces in `ui/ports.dart` and on
/// `TunnelController`, never on a concrete class. That is what makes the
/// placeholders swappable: when `lib/control/` and `lib/provision/` grow the
/// objects the UI calls, and when a real tunnel engine exists, the change is
/// three lines here and nothing else.
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  final ServerStore store = SecureServerStore();

  // The engine. Android only, and iOS is deliberately NOT wired here even
  // though singbox_tunnel now carries its half.
  //
  // What exists on iOS: the FlutterPlugin that drives NETunnelProviderManager,
  // the NEPacketTunnelProvider subclass, and the 27-method libbox
  // PlatformInterface behind it. What does not: the app extension TARGET those
  // last two have to be compiled into. It needs its own bundle identifier, its
  // own Network Extension entitlement and an App Group shared with this app,
  // none of which `flutter create` produces -- and app/ios/ is regenerated by
  // `flutter create` in CI on every run. Until that directory is committed with
  // the target in it (packages/singbox_tunnel/ios/README.md is the spec), an
  // iOS build has a plugin that can save a VPN configuration and nothing on the
  // other end of it.
  //
  // So iOS gets the stub, which is the honest answer for a build that cannot
  // tunnel. Wiring SingboxTunnel here would not lie -- every path it cannot
  // complete fails with text naming what is missing -- but it would turn "this
  // platform has no engine", said once at the composition root, into a failure
  // discovered per connect attempt, and it would claim the platform is done.
  //
  // Everywhere else this stays the stub too, which reports failure naming the
  // platform and the missing artifact and never reports connected. A stub that
  // showed "Connected" would be indistinguishable from a working app, and
  // somebody would route their traffic through it believing that.
  //
  // The builder is where the two halves meet: singbox_tunnel deliberately does
  // not know the configuration format -- importing lib/config/ from the package
  // would be the app -> package -> app cycle -- so the app supplies it, and
  // lib/config/ stays the single definition of what a share URI becomes.
  final TunnelController tunnel = Platform.isAndroid
      ? SingboxTunnel((TunnelProfile profile) => encodeSingBoxConfig(
            buildSingBoxConfig(
              outbound: selectOutbound(
                profile.importUris,
                // Never silently accept any certificate. The config layer
                // refuses to pick this for the caller, and the caller is here.
                // Since share() started publishing `spki`, a current Hysteria2
                // link is pinned by public key and this argument does not come
                // into it; a link issued before that will fail the handshake,
                // which is the honest outcome. The alternative -- anyCertificate
                // -- turns "this certificate" into "some TLS", and an app that
                // does that quietly is worse than one that fails loudly.
                hysteria2Trust: Hysteria2Trust.systemRoots,
              ),
            ),
          ))
      : UnimplementedTunnel();

  runApp(
    MultiProvider(
      // No explicit element type: SingleChildWidget reaches provider.dart
      // through a re-export, and inference does not need it named.
      providers: [
        // SSH itself. control/ and provision/ are complete and take their
        // transport injected, so this one object is what stands between this
        // app and a real server.
        //
        // It carries one obligation that is not optional:
        // `SshConnector.connect` is handed a HostKeyPolicy and applies it
        // during the key exchange, before authentication -- dartssh2 accepts
        // any host key when `onVerifyHostKey` is not supplied, and this app
        // asks for a root password on its second screen. `ui/access.dart`
        // decides the policy; honouring it is `transport/`'s half.
        //
        // `MissingSshTransport` stays in the tree as the honest fallback for a
        // platform where this one cannot run, and nothing wires it.
        Provider<SshTransport>.value(value: const Dartssh2Transport()),
        Provider<FileSaver>.value(value: const MissingFileSaver()),
        ChangeNotifierProvider<ServersModel>(
          create: (_) => ServersModel(store)..load(),
        ),
        ChangeNotifierProvider<CredentialVault>(
          create: (_) => CredentialVault(),
        ),
        ChangeNotifierProvider<TunnelModel>(
          create: (_) => TunnelModel(tunnel),
        ),
      ],
      child: const VpnStackApp(),
    ),
  );
}
